name: 'corvus-build'
description: 'Generate a comment showing Corvus comparisons'
branding:
  icon: 'box'
  color: 'purple'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 21 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Checkout ci-corvus
      uses: actions/checkout@v4
      with: 
        repository: nwxrichardson/ci-corvus
    - name: Checkout ci-corvus
      uses: actions/checkout@v4
      with: 
        repository: epsilonlabs/sirius-pr-action-workspace
        path: model
    - name: Move model
      run : mv $(pwd)/model/bundles/psl $(pwd)/bundles
      shell: bash
    - name: Move edit
      run : mv $(pwd)/model/bundles/psl.edit $(pwd)/bundles
      shell: bash
    - name: Move design
      run : mv $(pwd)/model/bundles/psl.design $(pwd)/bundles
      shell: bash
    - name: Maven Build
      run : mvn clean verify
      shell: bash
    - name: Tree
      run : tree
      shell: bash
    - name: Docker build
      run : docker build -t nwrichardson/ci-corvus:latest . 
      shell: bash
#    - name: Docker push
#      run : docker push nwrichardson/ci-corvus:latest
#      shell: bash
      
