name: 'corvus-build'
description: 'Generate a comment showing Corvus comparisons'
branding:
  icon: 'box'
  color: 'purple'
runs:
  using: 'composite'
  steps:
    - name: Checkout ci-corvus
      uses: actions/checkout@v4
      with: 
        repository: nwxrichardson/ci-corvus
#    - name: Checkout ci-corvus
#      uses: actions/checkout@v4
#      with: 
#        repository: epsilonlabs/sirius-pr-action-workspace
#        path: model
    - name: Docker build
      run : docker build -t nwrichardson/ci-corvus:latest . 
      shell: bash
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker push
      run : docker push nwrichardson/ci-corvus:latest
      shell: bash
      